version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "ms_balance2"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "qwerty"

    ports:
      - "5432:5432"
    volumes:
        - ./:/app